name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push
      run: |
        docker build --push --tag ${{ secrets.DOCKER_USERNAME }}/todo-app:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/todo-app:latest ${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.sha }}

    - name: Deploy to server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p $PASSWORD ssh $USERNAME@$HOST "docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app:latest && docker stop todo-app || true && docker rm todo-app || true && docker run -d -p 8080:80 --name todo-app ${{ secrets.DOCKER_USERNAME }}/todo-app:latest"
